//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="PTBCSMSGatewaySoap", Namespace="http://tempuri.org/")]
public partial class PTBCSMSGateway : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendBulkSMSOperationCompleted;
    
    /// <remarks/>
    public PTBCSMSGateway() {
        this.Url = ConfigurationManager.AppSettings["UrlGatewaySMS"];
    }
    
    /// <remarks/>
    public event SendSMSCompletedEventHandler SendSMSCompleted;
    
    /// <remarks/>
    public event SendBulkSMSCompletedEventHandler SendBulkSMSCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public RESPONSE SendSMS(string REQUEST_ID, string RECEIVER_ID, string PHONE_NBR, string MESSAGE, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME) {
        object[] results = this.Invoke("SendSMS", new object[] {
                    REQUEST_ID,
                    RECEIVER_ID,
                    PHONE_NBR,
                    MESSAGE,
                    SENDER_IP,
                    DATE,
                    USER_ID,
                    APPLICATION_NAME});
        return ((RESPONSE)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendSMS(string REQUEST_ID, string RECEIVER_ID, string PHONE_NBR, string MESSAGE, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendSMS", new object[] {
                    REQUEST_ID,
                    RECEIVER_ID,
                    PHONE_NBR,
                    MESSAGE,
                    SENDER_IP,
                    DATE,
                    USER_ID,
                    APPLICATION_NAME}, callback, asyncState);
    }
    
    /// <remarks/>
    public RESPONSE EndSendSMS(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((RESPONSE)(results[0]));
    }
    
    /// <remarks/>
    public void SendSMSAsync(string REQUEST_ID, string RECEIVER_ID, string PHONE_NBR, string MESSAGE, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME) {
        this.SendSMSAsync(REQUEST_ID, RECEIVER_ID, PHONE_NBR, MESSAGE, SENDER_IP, DATE, USER_ID, APPLICATION_NAME, null);
    }
    
    /// <remarks/>
    public void SendSMSAsync(string REQUEST_ID, string RECEIVER_ID, string PHONE_NBR, string MESSAGE, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME, object userState) {
        if ((this.SendSMSOperationCompleted == null)) {
            this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
        }
        this.InvokeAsync("SendSMS", new object[] {
                    REQUEST_ID,
                    RECEIVER_ID,
                    PHONE_NBR,
                    MESSAGE,
                    SENDER_IP,
                    DATE,
                    USER_ID,
                    APPLICATION_NAME}, this.SendSMSOperationCompleted, userState);
    }
    
    private void OnSendSMSOperationCompleted(object arg) {
        if ((this.SendSMSCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBulkSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public RESPONSE[] SendBulkSMS(REQUEST[] SMS_REQUEST, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME) {
        object[] results = this.Invoke("SendBulkSMS", new object[] {
                    SMS_REQUEST,
                    SENDER_IP,
                    DATE,
                    USER_ID,
                    APPLICATION_NAME});
        return ((RESPONSE[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendBulkSMS(REQUEST[] SMS_REQUEST, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendBulkSMS", new object[] {
                    SMS_REQUEST,
                    SENDER_IP,
                    DATE,
                    USER_ID,
                    APPLICATION_NAME}, callback, asyncState);
    }
    
    /// <remarks/>
    public RESPONSE[] EndSendBulkSMS(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((RESPONSE[])(results[0]));
    }
    
    /// <remarks/>
    public void SendBulkSMSAsync(REQUEST[] SMS_REQUEST, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME) {
        this.SendBulkSMSAsync(SMS_REQUEST, SENDER_IP, DATE, USER_ID, APPLICATION_NAME, null);
    }
    
    /// <remarks/>
    public void SendBulkSMSAsync(REQUEST[] SMS_REQUEST, string SENDER_IP, System.DateTime DATE, string USER_ID, string APPLICATION_NAME, object userState) {
        if ((this.SendBulkSMSOperationCompleted == null)) {
            this.SendBulkSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBulkSMSOperationCompleted);
        }
        this.InvokeAsync("SendBulkSMS", new object[] {
                    SMS_REQUEST,
                    SENDER_IP,
                    DATE,
                    USER_ID,
                    APPLICATION_NAME}, this.SendBulkSMSOperationCompleted, userState);
    }
    
    private void OnSendBulkSMSOperationCompleted(object arg) {
        if ((this.SendBulkSMSCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendBulkSMSCompleted(this, new SendBulkSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class RESPONSE {
    
    private string rEQUEST_IDField;
    
    private string rESP_CDField;
    
    private string rESP_MSGField;
    
    /// <remarks/>
    public string REQUEST_ID {
        get {
            return this.rEQUEST_IDField;
        }
        set {
            this.rEQUEST_IDField = value;
        }
    }
    
    /// <remarks/>
    public string RESP_CD {
        get {
            return this.rESP_CDField;
        }
        set {
            this.rESP_CDField = value;
        }
    }
    
    /// <remarks/>
    public string RESP_MSG {
        get {
            return this.rESP_MSGField;
        }
        set {
            this.rESP_MSGField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class REQUEST {
    
    private string rEQUEST_IDField;
    
    private string rECEIVER_IDField;
    
    private string pHONE_NBRField;
    
    private string mESSAGEField;
    
    /// <remarks/>
    public string REQUEST_ID {
        get {
            return this.rEQUEST_IDField;
        }
        set {
            this.rEQUEST_IDField = value;
        }
    }
    
    /// <remarks/>
    public string RECEIVER_ID {
        get {
            return this.rECEIVER_IDField;
        }
        set {
            this.rECEIVER_IDField = value;
        }
    }
    
    /// <remarks/>
    public string PHONE_NBR {
        get {
            return this.pHONE_NBRField;
        }
        set {
            this.pHONE_NBRField = value;
        }
    }
    
    /// <remarks/>
    public string MESSAGE {
        get {
            return this.mESSAGEField;
        }
        set {
            this.mESSAGEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public RESPONSE Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((RESPONSE)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void SendBulkSMSCompletedEventHandler(object sender, SendBulkSMSCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendBulkSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendBulkSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public RESPONSE[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((RESPONSE[])(this.results[0]));
        }
    }
}
